// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAExGwGC3g__DEeBRLlCP-rOdNlt6NYGoo',
    appId: '1:578402689454:web:541b4fdcdfc8659ac8e83f',
    messagingSenderId: '578402689454',
    projectId: 'globalink-41eb2',
    authDomain: 'globalink-41eb2.firebaseapp.com',
    storageBucket: 'globalink-41eb2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAauYc-cz4P-DwgVxEO2JIrfT_px_b7nQ',
    appId: '1:578402689454:android:d1df4b3c603d98a7c8e83f',
    messagingSenderId: '578402689454',
    projectId: 'globalink-41eb2',
    storageBucket: 'globalink-41eb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRV51k08A_-nrVH78rKrevzJm7ZOKDb1w',
    appId: '1:578402689454:ios:24a04042e1d712abc8e83f',
    messagingSenderId: '578402689454',
    projectId: 'globalink-41eb2',
    storageBucket: 'globalink-41eb2.appspot.com',
    iosBundleId: 'com.example.globalink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRV51k08A_-nrVH78rKrevzJm7ZOKDb1w',
    appId: '1:578402689454:ios:9b52d2b859245da3c8e83f',
    messagingSenderId: '578402689454',
    projectId: 'globalink-41eb2',
    storageBucket: 'globalink-41eb2.appspot.com',
    iosBundleId: 'com.example.globalink.RunnerTests',
  );
}
